name       : solarus-quest-editor
version    : 1.6.4
release    : 8
source     :
    - https://gitlab.com/solarus-games/solarus-quest-editor/-/archive/v1.6.4/solarus-quest-editor-v1.6.4.tar.bz2 : 2794e6bcfd865b34ff2962518398d24876a164fe0837d03f1a3614fb38810f8f
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : programming.tools
summary    : Quest editor for the Solarus ARPG engine
description: |
    Quest editor for the Solarus ARPG engine.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(glm)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(physfs)
    - solarus-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
