name       : solarus-quest-editor
version    : 1.6.0
release    : 7
source     :
    - https://gitlab.com/solarus-games/solarus-quest-editor/-/archive/v1.6.0/solarus-quest-editor-v1.6.0.tar.gz : 46fcd628539517973c800154c39c95445ad1e715930e58a7a2f16d853805cbe2
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : programming.tools
summary    : Quest editor for the Solarus ARPG engine
description: |
    Quest editor for the Solarus ARPG engine
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glm)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
    - physfs-devel
    - solarus-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
