name       : solarus-quest-editor
version    : 1.6.5
release    : 10
source     :
    - https://gitlab.com/solarus-games/solarus-quest-editor/-/archive/v1.6.5/solarus-quest-editor-v1.6.5.tar.bz2 : d556e5b02c943953beaf1bf1c42c3c7ce02ed5c1821789c47afdc3aed715540d
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : programming.tools
summary    : Quest editor for the Solarus ARPG engine
description: |
    Quest editor for the Solarus ARPG engine.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(glm)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(physfs)
    - solarus-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
