name       : solarus-quest-editor
version    : 1.5.0
release    : 1
source     :
    - https://github.com/christopho/solarus-quest-editor/archive/v1.5.0.tar.gz : 5cb3ccaca86512399625403eac02eceff62a3ec06830d8ff86585979ca2dfc6a
license    : 
    - CC-BY-SA-3.0
    - GPL-3.0
component  : programming.tools
summary    : Quest editor for the Solarus ARPG engine
description: |
    Quest editor for the Solarus ARPG engine
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gl)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(SDL2_image)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(ogg)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - physfs-devel
    - solarus-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install

    for i in 16 32 48 64 96 128 256 512 768 1024; do \
        install -D -m 00644 $workdir/images/icon/sqe-icon-png-"$i"px.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/solarus-quest-editor.png; \
    done
    install -D -m 00644 $pkgfiles/solarus-quest-editor.desktop $installdir/usr/share/applications/solarus-quest-editor.desktop